# The networked file system can be a little slow.
# Files can take up to 30 seconds to appear.
output-wait: 30

# If a job fails, retry it a couple of times in case it's a temporary issue.
# retries: 2

# Execute the workflow using Slurm jobs with no limit on the number
# of Slurm jobs created.
# Note: some rule executions will be grouped together,
# so one Slurm job may be several rule executions.
executor: slurm
jobs: unlimited
#cores: 128
#resources:
#    mem_mb: 500000

set-threads:
  all: 1
  download_faSplit: 1
  split_fasta: 1
  generate_all_indexes: 1
  generate_single_index: 1
  split_index_list: 1

default-resources:
  slurm_partition: short-cpu
  tasks: 1
  cpus_per_task: 1
  mem_mb_per_cpu: 500
  runtime: 15     # Runtime is measured in minutes.
  slurm_extra: '"--exclusive=user"'     # Notice both the single and double quotes.

#groups: '"generate_single_index=mygroup"'
#group-components: '"mygroup=5"'
